# Generated by Django 3.0.1 on 2020-01-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquirie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_phone_number', models.CharField(max_length=11)),
                ('Item_enquiry', models.CharField(max_length=2000)),
                ('enquiry_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Category', models.CharField(choices=[('Soft Drink', 'Soft Drink'), ('Confectionery', 'Confectionery'), ('Fitness Food', 'Fitness Food')], max_length=13)),
                ('Item_Name', models.CharField(max_length=2000)),
                ('Item_Picture', models.ImageField(blank=True, upload_to='before_and_afters/')),
                ('Item_Description', models.TextField()),
                ('Item_Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Item_Date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
