# Generated by Django 3.0.1 on 2020-01-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Item_Picture',
            field=models.ImageField(blank=True, upload_to='Product_Photos/'),
        ),
    ]
