# Generated by Django 3.0.1 on 2020-01-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200101_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirie',
            name='Extra_Info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquirie',
            name='customer_email',
            field=models.CharField(default='h', max_length=300),
            preserve_default=False,
        ),
    ]
